# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7f4d94449ed6d95dd138554401064869"
name = "learner-app"
handle = "learner-app-2"
application_url = "https://screensavers-inspired-summit-assumption.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "vladsdevstore.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://screensavers-inspired-summit-assumption.trycloudflare.com/auth/callback",
  "https://screensavers-inspired-summit-assumption.trycloudflare.com/auth/shopify/callback",
  "https://screensavers-inspired-summit-assumption.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
